import { MarketplaceProject } from '@/types/marketplace'

export const MARKETPLACE_PROJECTS: MarketplaceProject[] = [
  {
    id: 1,
    slug: 'khaki-crane-medical-platform',
    name: 'Plateforme Medicale SaaS',
    category: 'Medical',
    status: 'live',
    shortDesc: 'Plateforme medicale moderne orientee parcours patient et relation centre de soins.',
    fullDesc:
      'Application medicale orientee acquisition locale, presentation des soins et conversion des visiteurs en rendez-vous. Le parcours met en avant la prise en charge, les specialites du centre et des appels a l action clairs pour booster la reservation.',
    stack: ['Next.js', 'TypeScript', 'SEO local', 'UI/UX', 'Formulaires'],
    demoUrl: 'https://khaki-crane-381915.hostingersite.com',
    accentColor: '#7C6EFA',
    screenshot: '/screenshots/medical-cabinet.png',
  },
  {
    id: 2,
    slug: 'cupping-room',
    name: 'Cupping Room',
    category: 'Medical',
    status: 'live',
    shortDesc: 'Site medical premium pour hijama et cupping therapy a Marseille.',
    fullDesc:
      'Positionnement haut de gamme avec hero editorial, argumentaire medical rassurant et CTA de reservation immediats. Le site est construit pour inspirer confiance et augmenter le taux de prise de contact.',
    stack: ['Next.js', 'Landing', 'Conversion', 'Branding'],
    demoUrl: 'https://cupping-room.fr',
    accentColor: '#C084FC',
    screenshot: '/screenshots/cupping-room.png',
  },
  {
    id: 3,
    slug: 'attal-pl',
    name: 'Attal P.L. Marketplace',
    category: 'Garage et vente vehicule',
    status: 'live',
    shortDesc: 'Catalogue poids lourds et materiel TP avec fiches vehicules et contact rapide.',
    fullDesc:
      'Marketplace B2B dediee a la vente de poids lourds et materiel TP d occasion. La plateforme structure le stock par categories, valorise les annonces a la une et facilite la conversion vers appel ou demande d information.',
    stack: ['Catalogue', 'Filtres', 'B2B', 'SEO'],
    demoUrl: 'https://azure-wren-478191.hostingersite.com/',
    accentColor: '#F97316',
    screenshot: '/screenshots/attal-pl.png',
  },
  {
    id: 4,
    slug: 'gardanne-autos-pieces',
    name: 'Gardanne Autos Pieces',
    category: 'Garage et vente vehicule',
    status: 'live',
    shortDesc: 'Plateforme garage + vehicules + pieces avec mise en avant des services atelier.',
    fullDesc:
      'Vitrine complete pour garage automobile combinant prestations atelier, carrosserie, ventes vehicules et pieces. Le parcours utilisateur relie offre service et stock vehicules pour maximiser les demandes de rendez-vous.',
    stack: ['Automobile', 'Stock', 'Services', 'Landing'],
    demoUrl: 'https://bisque-swan-351965.hostingersite.com/',
    accentColor: '#EF4444',
    screenshot: '/screenshots/gardanne-gap.png',
  },
  {
    id: 5,
    slug: 'electrotech-enr',
    name: 'Electrotech ENR',
    category: 'Batiment',
    status: 'live',
    shortDesc: 'Vitrine electricite solaire avec argumentaire expertise et conversion locale.',
    fullDesc:
      'Presence digitale d un acteur electricite et ENR avec structure orientee confiance: certifications, cas clients, avis et call-to-action telephonique. Le site favorise la prise de devis en priorite.',
    stack: ['Energetique', 'SEO local', 'Avis clients'],
    demoUrl: 'https://electrotechenr.fr',
    accentColor: '#22C55E',
    screenshot: '/screenshots/electrotechenr.png',
  },
  {
    id: 6,
    slug: 'electrotech-13',
    name: 'Electrotech 13',
    category: 'Batiment',
    status: 'live',
    shortDesc: 'Site corporate electricien 40+ ans avec services, certifications et clients grands comptes.',
    fullDesc:
      'Site corporate complet structure pour rassurer les donneurs d ordre: historique, labels, references clients et services detailles. UX orientee conversion immediate vers appel et devis gratuit.',
    stack: ['Corporate', 'Confiance', 'SEO', 'Conversion'],
    demoUrl: 'https://electrotech-sud.fr/',
    accentColor: '#0EA5E9',
    screenshot: '/screenshots/electrotech13.png',
  },
  {
    id: 7,
    slug: 'keryaloc-gestion-locative',
    name: 'Keryaloc',
    category: 'Gestion locative',
    status: 'live',
    shortDesc: 'SaaS de location de vehicules premium en Algerie avec reservation en ligne et disponibilites synchronisees.',
    fullDesc:
      'Keryaloc est une solution SaaS de gestion locative automobile en Algerie. La plateforme couvre le catalogue vehicules, la reservation en ligne, la gestion des disponibilites en temps reel et le suivi client pour une exploitation fluide de l activite.',
    stack: ['SaaS', 'Gestion locative', 'Reservation', 'Catalogue', 'Temps reel'],
    demoUrl: 'https://darkcyan-kudu-431247.hostingersite.com/public/index.php',
    accentColor: '#3B82F6',
    screenshot: '/screenshots/keryaloc.png',
  },
  {
    id: 8,
    slug: 'hotelos-360',
    name: 'HôtelOS 360',
    category: 'Hotel et conciergerie',
    status: 'live',
    shortDesc: 'Site hotel haut de gamme avec moteur de reservation et PMS integre pour la gestion des sejours.',
    fullDesc:
      'Vitrine hoteliere complete autour de Setif : chambres et suites, formules de sejour, experiences locales et journal d invites. Le parcours integre la recherche de disponibilites, la composition du sejour et un espace client, le tout relie a un PMS pour exploiter reservations et sejours de bout en bout.',
    stack: ['Next.js', 'PMS', 'Reservation', 'Hotellerie', 'UX conversion'],
    demoUrl: 'https://olive-quetzal-411043.hostingersite.com/public/',
    accentColor: '#0D9488',
    screenshot: '/screenshots/hotel.png',
  },
]

export const MARKETPLACE_CATEGORIES = [
  'Toutes',
  'Medical',
  'Garage et vente vehicule',
  'Batiment',
  'SaaS metier',
  'Gestion locative',
  'Hotel et conciergerie',
] as const
